#ifndef _MCU_PWR_DEF_H
#define _MCU_PWR_DEF_H

typedef enum _enMPCOpCode
{
	MPC_OP_EEPROM		= 0x10,
	MPC_OP_POWCTRL		= 0x20,
	MPC_OP_VOLTAGE		= 0x30,
	MPC_OP_DETECT		= 0x40,
	MPC_OP_TEMP			= 0x50,
	MPC_OP_BOARDID		= 0x60,
	MPC_OP_FWREV		= 0x70,
	MPC_OP_NVMEMISTART	= 0x80,
	MPC_OP_NVMEMIREADY	= 0x81,
	MPC_OP_UPDATEFW		= 0x90,
	MPC_OP_DOWNLOADFW	= 0xA0,
	MPC_OP_RESET		= 0xB0,
	MPC_OP_NVMEMIDXFER	= 0xC0,
	MPC_OP_NVMEMIDRCVR	= 0xC1,
}enMPCOpCode;

#define	MPC_REQ_VAL_HEAD		0x55
#define	MPC_REQ_VAL_TAIL		0x33

#endif
